In [140]:
import numpy as np
import pandas as pd

In [141]:
anime = pd.read_csv('anime.csv')
rating = pd.read_csv('rating.csv')

In [142]:
anime.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [143]:
rating.head()

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [144]:
anime.merge(rating, on='anime_id')

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,278,-1
...,...,...,...,...,...,...,...,...,...
7813722,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,39532,-1
7813723,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,48766,-1
7813724,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,60365,4
7813725,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,27364,-1
7813726,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,48766,-1

In [145]:
anime.duplicated().sum()

0

In [146]:
anime.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [147]:
anime = anime[['anime_id', 'name', 'genre', 'rating']]

In [148]:
anime.head()

,anime_id,name,genre,rating
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",9.26
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",9.25
3,9253,Steins;Gate,"Sci-Fi, Thriller",9.17
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",9.16

In [149]:
anime['genre'] = anime['genre'].astype(str).apply(lambda x: x.lower())

In [150]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [151]:
def stem(text):
    return ' '.join([ps.stem(word) for word in text.split()])

In [152]:
anime['genre'] = anime['genre'].apply(stem)
anime['genre'].head()

0                   drama, romance, school, supernatur
1    action, adventure, drama, fantasy, magic, mili...
2    action, comedy, historical, parody, samurai, s...
3                                     sci-fi, thriller
4    action, comedy, historical, parody, samurai, s...
Name: genre, dtype: object

In [153]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000 , stop_words='english')

In [154]:
vector = cv.fit_transform(anime['genre']).toarray()

In [155]:
from sklearn.metrics.pairwise import cosine_similarity

In [168]:
similarity = cosine_similarity(vector)
def get_recommendations(title):
    index = anime[anime['name'] == title].index[0]
    sim_scores = list(enumerate(similarity[index]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    anime_indices = [i[0] for i in sim_scores]
    anime_name = anime.iloc[anime_indices]['name']
    return anime_name

In [169]:
get_recommendations('Gintama&#039;')

4                                            Gintama&#039;
8        Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...
9                                 Gintama&#039;: Enchousen
12                                                 Gintama
63             Gintama: Yorinuki Gintama-san on Theater 2D
65                  Gintama Movie: Shinyaku Benizakura-hen
216                       Gintama: Shinyaku Benizakura-hen
306                       Gintama: Jump Festa 2014 Special
10896                                       Gintama (2017)
380      Gintama: Nanigoto mo Saiyo ga Kanjin nano de T...
Name: name, dtype: object

In [158]:
import pickle 
pickle.dump(anime.to_dict(), open('Anime.pkl','wb'))
pickle.dump(similarity, open('Anime_similarity.pkl','wb'))

In [159]:
anime

,anime_id,name,genre,rating
0,32281,Kimi no Na wa.,"drama, romance, school, supernatur",9.37
1,5114,Fullmetal Alchemist: Brotherhood,"action, adventure, drama, fantasy, magic, mili...",9.26
2,28977,Gintama°,"action, comedy, historical, parody, samurai, s...",9.25
3,9253,Steins;Gate,"sci-fi, thriller",9.17
4,9969,Gintama&#039;,"action, comedy, historical, parody, samurai, s...",9.16
...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,hentai,4.15
12290,5543,Under World,hentai,4.28
12291,5621,Violence Gekiga David no Hoshi,hentai,4.88
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,hentai,4.98
12293,26081,Yasuji no Pornorama: Yacchimae!!,hentai,5.46

In [160]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [166]:
def recommend_anime(title):
    idx = anime[anime['name'] == title].index[0]
    sim_scores = list(enumerate(similarity[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]

    recd_anime = []
    recd_anime_poster = []
    for i in sim_scores:
        anime_id = anime.iloc[i[0]]['anime_id']
        recd_anime.append(anime.iloc[i[0]].name)
        recd_anime_poster.append(fetch_poster_anime(anime_id))
    return recd_anime, recd_anime_poster


def fetch_poster_anime(anime_id):
    htmldata = urlopen(f'https://myanimelist.net/anime/{anime_id}')
    soup = BeautifulSoup(htmldata, 'html.parser')
    images = soup.find_all('img')
    link = images[1]['data-src']
    return link

In [167]:
recommend_anime('Gintama&#039;')

([4, 8, 9, 12, 63, 65, 216, 306, 10896, 380],
 ['https://cdn.myanimelist.net/images/anime/4/50361.jpg',
  'https://cdn.myanimelist.net/images/anime/10/51723.jpg',
  'https://cdn.myanimelist.net/images/anime/1452/123686.jpg',
  'https://cdn.myanimelist.net/images/anime/10/73274.jpg',
  'https://cdn.myanimelist.net/images/anime/1172/90571.jpg',
  'https://cdn.myanimelist.net/images/anime/4/28803.jpg',
  'https://cdn.myanimelist.net/images/anime/12/26966.jpg',
  'https://cdn.myanimelist.net/images/anime/1327/110925.jpg',
  'https://cdn.myanimelist.net/images/anime/3/83528.jpg',
  'https://cdn.myanimelist.net/images/anime/4/8522.jpg'])